const stock = [
    {
        id: 0,
        producto: "Coca 237ml",
        stockSistema: 27,
        stockDeposito: 21,
    },
    {
        id: 1,
        producto: "Coca lata 354ml",
        stockSistema: 5,
        stockDeposito: 0,
    },
    {
        id: 2,
        producto: "Coca lata 473ml",
        stockSistema: 6,
        stockDeposito: 0,
    },
    {
        id: 3,
        producto: "Coca 500ml",
        stockSistema: 169,
        stockDeposito: 87,
    },
    {
        id: 4,
        producto: "Coca 1.75L",
        stockSistema: 18,
        stockDeposito: 13,
    },
    {
        id: 5,
        producto: "Coca 2.25L",
        stockSistema: 22,
        stockDeposito: 22,
    },
    {
        id: 6,
        producto: "Powerade",
        stockSistema: 17,
        stockDeposito: 18,
    },
    {
        id: 7,
        producto: "Aquarius 500ml",
        stockSistema: 21,
        stockDeposito: 12,
    },
    {
        id: 8,
        producto: "Aquarius 1.5L",
        stockSistema: 8,
        stockDeposito: 0,
    },
    {
        id: 9,
        producto: "Monster",
        stockSistema: 66,
        stockDeposito: 27,
    },
    {
        id: 10,
        producto: "Cepita 200ml",
        stockSistema: 29,
        stockDeposito: 19,
    },

    {
        id: 11,
        producto: "Cepita 1L",
        stockSistema: 39,
        stockDeposito: 20,
    },
    {
        id: 12,
        producto: "Smart 500ml",
        stockSistema: 16,
        stockDeposito: 14,
    },
    {
        id: 13,
        producto: "Smart 1L",
        stockSistema: 5,
        stockDeposito: 1,
    },
    {
        id: 14,
        producto: "Schweppes lata",
        stockSistema: 8,
        stockDeposito: 0,
    },
    {
        id: 15,
        producto: "Pepsi 250ml",
        stockSistema: 69,
        stockDeposito: 36,
    },
    {
        id: 16,
        producto: "Pepsi lata",
        stockSistema: 12,
        stockDeposito: 12,
    },
    {
        id: 17,
        producto: "Pepsi 500ml",
        stockSistema: 174,
        stockDeposito: 102,
    },
    {
        id: 18,
        producto: "Pepsi 1.5L",
        stockSistema: 32,
        stockDeposito: 28,
    },
    {
        id: 19,
        producto: "Pepsi 2L",
        stockSistema: 48,
        stockDeposito: 41,
    },
    {
        id: 20,
        producto: "Red Bull 250ml",
        stockSistema: 15,
        stockDeposito: 15,
    },
    {
        id: 21,
        producto: "Red Bull 355ml",
        stockSistema: 8,
        stockDeposito: 8,
    },
    {
        id: 22,
        producto: "Gatorade",
        stockSistema: 38,
        stockDeposito: 12,
    },
    {
        id: 23,
        producto: "Glaciar 500ml",
        stockSistema: 18,
        stockDeposito: 5,
    },
    {
        id: 24,
        producto: "Glaciar 1L",
        stockSistema: 8,
        stockDeposito: 5,
    },
    {
        id: 25,
        producto: "Villavicencio 500ml",
        stockSistema: 78,
        stockDeposito: 0,
    },
    {
        id: 26,
        producto: "Villavicencio 750ml",
        stockSistema: 0,
        stockDeposito: 0,
    },
    {
        id: 27,
        producto: "Villavicencio 1L",
        stockSistema: 40,
        stockDeposito: 14,
    },
    {
        id: 28,
        producto: "Villavicencio 2L",
        stockSistema: 22,
        stockDeposito: 18,
    },
    {
        id: 29,
        producto: "Levite 500ml",
        stockSistema: 67,
        stockDeposito: 12,
    },
    {
        id: 30,
        producto: "Levite 1L",
        stockSistema: 26,
        stockDeposito: 6,
    },
    {
        id: 31,
        producto: "Levite Fizz",
        stockSistema: 21,
        stockDeposito: 0,
    },
    {
        id: 32,
        producto: "Speed 250ml",
        stockSistema: 19,
        stockDeposito: 12,
    },
    {
        id: 33,
        producto: "Speed 500ml",
        stockSistema: 11,
        stockDeposito: 7,
    },
    {
        id: 34,
        producto: "Villa del Sur",
        stockSistema: 22,
        stockDeposito: 12,
    },
    {
        id: 35,
        producto: "Baggio 200ml",
        stockSistema: 75,
        stockDeposito: 44,
    },
    {
        id: 36,
        producto: "Baggio 1L",
        stockSistema: 21,
        stockDeposito: 8,
    },
    {
        id: 37,
        producto: "Citric 250ml",
        stockSistema: 23,
        stockDeposito: 0,
    },
    {
        id: 38,
        producto: "Citric 500ml",
        stockSistema: 15,
        stockDeposito: 0,
    },
    {
        id: 39,
        producto: "Citric 1L",
        stockSistema: 16,
        stockDeposito: 0,
    },
    {
        id: 40,
        producto: "Nesquik",
        stockSistema: 18,
        stockDeposito: 0,
    },
    {
        id: 41,
        producto: "Eco 500ml",
        stockSistema: 6,
        stockDeposito: 0,
    },
    {
        id: 42,
        producto: "BC 250ml",
        stockSistema: 33,
        stockDeposito: 24,
    },
    {
        id: 43,
        producto: "Arcor 250ml",
        stockSistema: 66,
        stockDeposito: 48,
    },
];
